app:
  jwt:
    secret: doSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlFdoSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlF
    refresh:
      expirationMinutes: 360
    access:
      expirationMinutes: 60
  wiki:
    username: info@iotiq.net
    password: iotiqWiki1
    strategy: local
    baseUrl: https://dev-wiki.culturati.app/graphql/
spring:
  profiles:
    active: dev
mapFileDirectory: file:./files/
tenantPropertiesPath: tenants
