#   README
#
#   Copy this file and rename to `application-dev.yml`. Then replace the placeholders with your own credentials.
#   Do not commit the file you've created!
#
app:
  wiki:
    username: info@iotiq.net
    password: iotiqWiki1
    strategy: local
    baseUrl: https://dev-wiki.culturati.app/graphql/
defaultTenant: tenant_1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    com:
#      iotiq:
#        abakus:
#          config:
#            RequestLogger: debug
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace
