defaultTenant: tenant_1
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  allowed-public-apis:
    - /swagger-ui/*
    - /v3/api-docs
    - /v3/api-docs/*
    - /api/v1/auth/*
    - /api/v1/test/*
seed:
  users:
    admin:
      username: admin
      password: admin123

app:
  jwt:
    secret: doSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlFdoSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlF
    refresh:
      expirationMinutes: 360
    access:
      expirationMinutes: 60
