#   README
#
#   Copy this file and rename to `application-dev.yml`. Then replace the placeholders with your own credentials.
#   Do not commit the file you've created!
#
app:
  jwt:
    secret: doSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlFdoSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlF
    refresh:
      expirationMinutes: 360
    access:
      expirationMinutes: 60
  wiki:
    username: info@iotiq.net
    password: iotiqWiki1
    strategy: local
    baseUrl: https://dev-wiki.culturati.app/graphql/
defaultTenant: tenant_1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

security:
  allowed-public-apis:
    - /swagger-ui/*
    - /v3/api-docs
    - /v3/api-docs/*
    - /api/v1/auth/*
    - /api/v1/test/*

#logging:
#  level:
#    com:
#      iotiq:
#        abakus:
#          config:
#            RequestLogger: debug
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace
