#   README
#
#   Copy this file and rename to `application-dev.yml`. Then replace the placeholders with your own credentials.
#   Do not commit the file you've created!
#

defaultTenant: tenant_1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

security:
  allowed-public-apis:
    - /swagger-ui/*
    - /actuator/**
    - /v3/api-docs
    - /v3/api-docs/*
    - /api/v1/auth/*
    - /api/v1/test/*
    - /api/v1/register
    - /api/v1/common/*
seed:
  users:
    admin:
      username: admin
      password: admin123

#logging:
#  level:
#    com:
#      iotiq:
#        abakus:
#          config:
#            RequestLogger: debug
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace
