spring:
  profiles:
    active: dev
mapFileDirectory: file:./files/

security:
  allowed-public-apis:
    - /swagger-ui/*
    - /v3/api-docs
    - /v3/api-docs/*
    - /api/v1/auth/*
    - /api/v1/test/*